### ISSUE TITLE
systemctl 起動失敗リスト on CentOS7

### ISSUE THREAD

**Issue by h-imaoka** [cloudpack/cloudpack-ami#3]
元のAMIから弄りまくっているので、本当に再現するか怪しいですが。まとめます
# systemctlの赤文字

AMI起動して、 systemctl を打って、赤字になっているものを白字に直していく
## network.service

一件ひやっとするが、サービス的には問題なし。インターフェース名は、新ルールと旧ルール(eth0系)で意見が割れるかもしれませんが、個人的に eth0を支持。
解決方法は下記っぽい(レビューキボンヌ)

```
rm /etc/sysconfig/network-scripts/ifcfg-enp0s3
rm /etc/udev/rules.d/70-persistent-net.rules
```

https://www.reddit.com/r/sysadmin/comments/2ldibo/issue_with_vmware_network_interfaces/
## postfix.service

メッセージの通りです

``` /etc/postfix/main.cf
# Enable IPv4, and IPv6 if supported
inet_protocols = ipv4
```
## kdump.service

t2.micro とかだとメモリ不足でそもそも動かない。
m3.midiumあたりでちゃんと動くので、無視

**Comment by saitara** [comment]
# 対処内容

template.jsonに頑張っていただきました。

## 事前準備

cloud-initでbootcmdによるInstanceStoreマウントをしていた部分をなくしました。
実害はありませんが、実害がないのであればエラー状態を記さないようにしておく方向です。

## network.service

```
systemctl enable NetworkManager-wait-online.service
```

## postfix.service

```
sed -i.bak 's@inet_protocols(*)=(.*)@inet_protocols = ipv4@g' /etc/postfix.conf
```

## kdump.service

```
systemctl disable kdump.service
```
